/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

export {}

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    Center: typeof import('./src/shortcuts/Center.vue')['default']
    Nav: typeof import('./src/components/Nav.vue')['default']
    NavBar: typeof import('./src/components/NavBar.vue')['default']
    PageList: typeof import('./src/components/PageList.vue')['default']
    PageMeta: typeof import('./src/components/PageMeta.vue')['default']
  }
}
