name: SyncIssues
on:
  discussion:
    types: [edited, deleted, locked, unlocked, labeled, pinned]

env:
  token: ${{ secrets.TOKEN }}
  user: fzdwx
  repo: fzdwx.github.io
  timeline: 4

jobs:
  update-tilemine:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/setup-go@v4
        with:
          go-version: 1.20.2
      - uses: actions/checkout@v3
      - run: go install .
      - run: bang version
      - run: bang feed
      - run: git config --global user.name "github.action"
      - run: git config --global user.email "action@github.com"
      - run: |
          if ! git diff --quiet --exit-code public/links.json; then
            git add public/links.json
            git commit -m "update links.json"
            git push
          else
            echo "public/links.json not modified."
          fi
