name: update_timeline
on:
  discussion:
    types: [ edited, deleted, locked, unlocked, labeled, pinned,created ]
  discussion_comment:
    types: [ edited, deleted, created ]

env:
  token: ${{ secrets.TOKEN }}
  user: fzdwx
  repo: fzdwx.github.io
  timeline: 4

jobs:
  update-tilemine:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/setup-go@v4
        with:
          go-version: 1.20.2
      - uses: actions/checkout@v3
      - run: go install .
      - run: bang version
      - run: bang tl
      - run: git config --global user.name "github.action"
      - run: git config --global user.email "action@github.com"
      - run: |
          if ! git diff --quiet --exit-code public/timeline.json; then
            git add public/timeline.json
            git commit -m "update timeline.json"
            git push
          else
            echo "public/timeline.json not modified."
          fi
